// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYRtJpdNxzeDz5a1uHhpP1MiBE4xBY4cE',
    appId: '1:445161071493:web:16cb1c5af82a0c41611aec',
    messagingSenderId: '445161071493',
    projectId: 'eproject-c9c8b',
    authDomain: 'eproject-c9c8b.firebaseapp.com',
    storageBucket: 'eproject-c9c8b.appspot.com',
    measurementId: 'G-8R3RTBR26L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3uw1FL38IZg91ybc4vYM221jXkxDaZo',
    appId: '1:445161071493:android:63bbae53c6974d44611aec',
    messagingSenderId: '445161071493',
    projectId: 'eproject-c9c8b',
    storageBucket: 'eproject-c9c8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTFiHVlVJO8aT3XP6o2rxuR5CKxMmtpHI',
    appId: '1:445161071493:ios:13b678c1ef5366d1611aec',
    messagingSenderId: '445161071493',
    projectId: 'eproject-c9c8b',
    storageBucket: 'eproject-c9c8b.appspot.com',
    iosBundleId: 'com.example.pr212c1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTFiHVlVJO8aT3XP6o2rxuR5CKxMmtpHI',
    appId: '1:445161071493:ios:e4ec6d150f86c8ae611aec',
    messagingSenderId: '445161071493',
    projectId: 'eproject-c9c8b',
    storageBucket: 'eproject-c9c8b.appspot.com',
    iosBundleId: 'com.example.pr212c1.RunnerTests',
  );
}
